name: Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: macos-latest
    strategy:
      matrix:
        BUILD_TARGET:
          - iOS
          - Android

    steps:
      - uses: actions/checkout@v3

      - name: Install Unity
        run: |
          brew install --cask unity

      - uses: akiojin/unity-get-version-github-action@v1.1.6

      - uses: akiojin/unity-build-github-action@v3.8.0
        with:
          build-target: ${{ matrix.BUILD_TARGET }}
          project-directory: ${{ github.workspace }}
