name: Build

on:
  push:
    branches:
      - main

jobs:
  Build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install git-credential-manager-core
        run: |
          brew tap microsoft/git
          brew install --cask git-credential-manager-core

      - name: Install Unity
        run: |
          brew install --cask unity

      - uses: akiojin/unity-get-version-github-action@v1.1.4

      - uses: akiojin/unity-build-github-action@v3.2.2
        with:
          build-target: 'iOS'
          project-directory: ${{ github.workspace }}
